# Generated by Django 5.2.7 on 2025-10-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('capital', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField()),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('estimated_gdp', models.FloatField(blank=True, null=True)),
                ('flag_url', models.URLField(blank=True, max_length=500, null=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('total_countries', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Refresh Status',
                'verbose_name_plural': 'Refresh Status',
            },
        ),
    ]
